spring:
  datasource:
    url: jdbc:h2:mem:~/foodwalletApplication
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    com.com.foodwallet: debug

jwt:
  secret: fasdhuikfghdusiogvyoasgi3198gw9fdjlscbvsasdasdasdasdcasf

file:
  dir: root
